import Head from 'next/head'
import Image from 'next/image'
import AppComponent from '../components/AppComponent'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolios.ltd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppComponent />
    </>
  )
}
